function OnEvent(event, arg)
    OutputLogMessage("event = %s, arg = %d\n", event, arg)
    if (event == "PROFILE_ACTIVATED") then
        EnablePrimaryMouseButtonEvents(true)
    elseif event == "PROFILE_DEACTIVATED" then
        ReleaseMouseButton(2)  -- to prevent it from being stuck on
    end
    if (event == "MOUSE_BUTTON_PRESSED" and arg == 5) then
        recoil = not recoil
        spot = not spot
    end
   if (event == "MOUSE_BUTTON_PRESSED" and arg == 1 and recoil) then
        if recoil then
            repeat
                Sleep(23)
MoveMouseRelative(0, 15)
                Sleep(24)
MoveMouseRelative(0, 15)
                Sleep(24)
MoveMouseRelative(0, 12)
                Sleep(24)
MoveMouseRelative(0, 12)
                Sleep(24)
MoveMouseRelative(0, 15)
                Sleep(24)
MoveMouseRelative(0, 15)
                Sleep(24)
MoveMouseRelative(0, 12)
                Sleep(24)
MoveMouseRelative(0, 12)
                Sleep(24)
MoveMouseRelative(3, 12)
                Sleep(24)
                if not IsMouseButtonPressed(1) then break end
MoveMouseRelative(3, 12)
                Sleep(24)
MoveMouseRelative(3, 15)
                Sleep(24)
MoveMouseRelative(9, 15)
                Sleep(24)
MoveMouseRelative(12, 15)
                Sleep(24)
MoveMouseRelative(12, 12)
                Sleep(24)
MoveMouseRelative(12, 12)
                Sleep(24)
MoveMouseRelative(9, 12)
                Sleep(24)
MoveMouseRelative(12, 12)
                Sleep(24)
MoveMouseRelative(12, 9)
                Sleep(24)
MoveMouseRelative(12, 9)
                Sleep(24)
MoveMouseRelative(12, 12)
                if not IsMouseButtonPressed(1) then break end
                Sleep(24)
MoveMouseRelative(12, 9)
                Sleep(24)
MoveMouseRelative(12, 9)
                Sleep(24)
MoveMouseRelative(9, 9)
                Sleep(24)
MoveMouseRelative(9, 9)
                Sleep(24)
MoveMouseRelative(9, 9)
                Sleep(24)
MoveMouseRelative(6, 6)
                Sleep(24)
MoveMouseRelative(6, 6)
                Sleep(24)
MoveMouseRelative(-3, 6)
                Sleep(24)
MoveMouseRelative(-3, 6)
                Sleep(24)
MoveMouseRelative(-6, 3)
                Sleep(24)
MoveMouseRelative(-6, 3)
                Sleep(24)
MoveMouseRelative(-9, 6)
                Sleep(24)
MoveMouseRelative(-9, 3)
                if not IsMouseButtonPressed(1) then break end
                Sleep(24)
MoveMouseRelative(-9, 3)
                Sleep(24)
MoveMouseRelative(-6, 3)
                Sleep(24)
MoveMouseRelative(-9, 3)
                Sleep(24)
MoveMouseRelative(-9, 3)
                Sleep(24)
MoveMouseRelative(-9, 6)
                Sleep(24)
MoveMouseRelative(-6, 6)
                Sleep(24)
MoveMouseRelative(-6, 6)
                Sleep(24)
MoveMouseRelative(-3, 6)
                Sleep(24)
MoveMouseRelative(-3, 3)
                Sleep(24)
MoveMouseRelative(-3, 3)
                Sleep(24)
MoveMouseRelative(0, 3)
                Sleep(24)
MoveMouseRelative(0, 3)
                Sleep(24)
MoveMouseRelative(0, 3)
                Sleep(24)
MoveMouseRelative(0, 3)
                Sleep(24)
MoveMouseRelative(0, 3)
                Sleep(24)
MoveMouseRelative(0, 3)
                Sleep(24)
MoveMouseRelative(0, 3)
                Sleep(24)
MoveMouseRelative(0, 3)
                Sleep(24)
MoveMouseRelative(6, 3)
                Sleep(24)
MoveMouseRelative(6, 3)
                Sleep(24)
MoveMouseRelative(6, 3)
                Sleep(24)
                if not IsMouseButtonPressed(1) then break end
MoveMouseRelative(6, 3)
                Sleep(24)
MoveMouseRelative(6, 0)
                Sleep(24)
MoveMouseRelative(6, 3)
                Sleep(24)
MoveMouseRelative(9, 0)
                Sleep(24)
MoveMouseRelative(9, 3)
                Sleep(24)
MoveMouseRelative(9, 0)
                Sleep(24)
MoveMouseRelative(9, 3)
                Sleep(24)
MoveMouseRelative(6, 0)
                Sleep(24)
MoveMouseRelative(6, 3)
                Sleep(24)
MoveMouseRelative(6, 0)
                Sleep(24)
MoveMouseRelative(6, 0)
                Sleep(24)
MoveMouseRelative(6, 0)
                Sleep(24)
MoveMouseRelative(6, 0)
                Sleep(24)
MoveMouseRelative(-3, 0)
                Sleep(24)
MoveMouseRelative(-3, 0)
                Sleep(24)
MoveMouseRelative(-3, 0)
                Sleep(24)
MoveMouseRelative(-3, 0)
                Sleep(24)
MoveMouseRelative(-3, 0)
                Sleep(24)
MoveMouseRelative(-3, 0)
                Sleep(24)
                if not IsMouseButtonPressed(1) then break end
MoveMouseRelative(-3, 0)
                Sleep(24)
MoveMouseRelative(-3, 0)
                Sleep(24)
MoveMouseRelative(-3, 0)
                Sleep(24)
MoveMouseRelative(-3, 0)
                Sleep(24)
MoveMouseRelative(-3, 0)
                Sleep(24)
MoveMouseRelative(-6, 0)
                Sleep(24)
MoveMouseRelative(-6, 0)
                Sleep(24)
MoveMouseRelative(-3, 0)
                Sleep(24)
MoveMouseRelative(-3, 0)
                Sleep(24)
MoveMouseRelative(-6, 0)
                Sleep(24)
MoveMouseRelative(-6, 0)
                Sleep(24)
MoveMouseRelative(-6, 0)
                Sleep(24)
MoveMouseRelative(-6, 0)
                Sleep(24)
MoveMouseRelative(-6, 0)
                Sleep(24)
MoveMouseRelative(-6, 0)
                Sleep(24)
MoveMouseRelative(-6, 0)
                Sleep(24)
MoveMouseRelative(-6, 0)
                Sleep(24)
MoveMouseRelative(-6, 0)
                Sleep(24)
MoveMouseRelative(-6, 0)
                Sleep(24)
MoveMouseRelative(-6, 0)
                Sleep(24)
MoveMouseRelative(-6, 0)
                Sleep(24)
MoveMouseRelative(-3, 0)
                Sleep(24)
MoveMouseRelative(-3, 0)
                Sleep(24)
MoveMouseRelative(-6, 0)
                Sleep(24)
MoveMouseRelative(-6, 0)
                Sleep(24)
MoveMouseRelative(-3, 0)
                Sleep(24)
                if not IsMouseButtonPressed(1) then break end
MoveMouseRelative(-3, 0)
                Sleep(24)
MoveMouseRelative(-6, 0)
                Sleep(24)
MoveMouseRelative(-3, 0)
                Sleep(24)
MoveMouseRelative(-3, 0)
                Sleep(24)
MoveMouseRelative(-3, 0)
                Sleep(24)
MoveMouseRelative(-6, 0)
                Sleep(24)
MoveMouseRelative(-6, 0)
                if not IsMouseButtonPressed(1) then break end
                Sleep(24)
MoveMouseRelative(-3, 0)
                Sleep(24)
MoveMouseRelative(-3, 0)
                Sleep(24)
MoveMouseRelative(-3, 0)
                Sleep(24)
MoveMouseRelative(-3, 0)
                Sleep(24)
MoveMouseRelative(-3, 0)
                Sleep(24)
MoveMouseRelative(-3, 0)
                Sleep(23)
                if not IsMouseButtonPressed(1) then break end
                PressAndReleaseMouseButton(1)
                Sleep(25)


                
                



            until not IsMouseButtonPressed(1)
        end
    end
end