function OnEvent(event, arg)
    OutputLogMessage("event = %s, arg = %d\n", event, arg)
    if (event == "PROFILE_ACTIVATED") then
        EnablePrimaryMouseButtonEvents(true)
    elseif event == "PROFILE_DEACTIVATED" then
        ReleaseMouseButton(2)  -- to prevent it from being stuck on
    end
    if (event == "MOUSE_BUTTON_PRESSED" and arg == 5) then
        recoil = not recoil
        spot = not spot
    end
   if (event == "MOUSE_BUTTON_PRESSED" and arg == 1 and recoil) then
        if recoil then
            repeat
                --Sleep(19)
                Sleep(58)
MoveMouseRelative(-11, 44)
Sleep(29)
MoveMouseRelative(-6, 28)
Sleep(29)
MoveMouseRelative(-6, 28)
Sleep(29)
MoveMouseRelative(-11, 28)
Sleep(29)
MoveMouseRelative(-6, 28)
Sleep(29)
MoveMouseRelative(-6, 22)
Sleep(29)
MoveMouseRelative(-6, 22)
Sleep(29)
MoveMouseRelative(0, 28)
Sleep(29)
MoveMouseRelative(6, 28)
Sleep(29)
MoveMouseRelative(0, 28)
if not IsMouseButtonPressed(1) then break end
Sleep(29)
MoveMouseRelative(6, 22)
Sleep(29)
MoveMouseRelative(6, 28)
Sleep(29)
MoveMouseRelative(6, 28)
Sleep(29)
MoveMouseRelative(11, 22)
Sleep(29)
MoveMouseRelative(11, 22)
Sleep(29)
MoveMouseRelative(6, 22)
Sleep(29)
MoveMouseRelative(6, 22)
Sleep(29)
MoveMouseRelative(11, 22)
Sleep(29)
MoveMouseRelative(11, 22)
if not IsMouseButtonPressed(1) then break end
Sleep(29)
MoveMouseRelative(11, 22)
Sleep(29)
MoveMouseRelative(11, 22)
Sleep(29)
MoveMouseRelative(6, 17)
Sleep(29)
MoveMouseRelative(6, 17)
Sleep(29)
MoveMouseRelative(0, 11)
Sleep(29)
MoveMouseRelative(6, 11)
Sleep(29)
MoveMouseRelative(0, 11)
Sleep(29)
MoveMouseRelative(0, 11)
Sleep(29)
MoveMouseRelative(-6, 11)
Sleep(29)
MoveMouseRelative(-6, 11)
Sleep(29)
MoveMouseRelative(-11, 11)
if not IsMouseButtonPressed(1) then break end
Sleep(29)
MoveMouseRelative(-11, 11)
Sleep(29)
MoveMouseRelative(-11, 11)
Sleep(29)
MoveMouseRelative(-11, 6)
Sleep(29)
MoveMouseRelative(-6, 6)
Sleep(29)
MoveMouseRelative(-6, 11)
Sleep(29)
MoveMouseRelative(-11, 11)
Sleep(29)
MoveMouseRelative(-11, 11)
Sleep(29)
MoveMouseRelative(-6, 11)
Sleep(29)
MoveMouseRelative(-6, 6)
Sleep(29)
MoveMouseRelative(-6, 11)
Sleep(29)
MoveMouseRelative(-6, 11)
Sleep(29)
MoveMouseRelative(-6, 6)
Sleep(29)
MoveMouseRelative(-6, 6)
Sleep(29)
if not IsMouseButtonPressed(1) then break end

MoveMouseRelative(-6, 11)
Sleep(29)
MoveMouseRelative(-6, 11)
Sleep(29)
MoveMouseRelative(-6, 6)
Sleep(29)
MoveMouseRelative(-6, 6)
Sleep(29)
MoveMouseRelative(11, 11)
Sleep(29)
MoveMouseRelative(11, 11)
Sleep(29)
MoveMouseRelative(11, 6)
Sleep(29)
MoveMouseRelative(11, 6)
Sleep(29)
MoveMouseRelative(11, 11)
Sleep(29)
if not IsMouseButtonPressed(1) then break end
MoveMouseRelative(11, 6)
Sleep(29)
MoveMouseRelative(6, 6)
Sleep(29)
MoveMouseRelative(6, 6)
Sleep(29)
MoveMouseRelative(6, 6)
Sleep(29)
MoveMouseRelative(6, 6)
Sleep(29)
MoveMouseRelative(6, 6)
Sleep(29)
MoveMouseRelative(0, 6)
Sleep(29)
MoveMouseRelative(6, 11)
Sleep(29)
MoveMouseRelative(0, 6)
Sleep(29)
MoveMouseRelative(0, 6)
Sleep(29)
MoveMouseRelative(6, 6)
Sleep(29)
MoveMouseRelative(0, 6)
Sleep(29)
MoveMouseRelative(0, 6)
if not IsMouseButtonPressed(1) then break end
Sleep(29)
MoveMouseRelative(0, 6)
Sleep(29)
MoveMouseRelative(0, 6)
Sleep(29)
MoveMouseRelative(0, 11)
Sleep(29)
MoveMouseRelative(0, 6)
Sleep(29)
MoveMouseRelative(0, 6)
Sleep(29)
MoveMouseRelative(0, 6)
if not IsMouseButtonPressed(1) then break end
Sleep(29)
MoveMouseRelative(0, 6)
Sleep(29)
MoveMouseRelative(0, 6)
Sleep(29)
MoveMouseRelative(0, 6)
Sleep(29)
MoveMouseRelative(0, 6)
Sleep(29)
MoveMouseRelative(0, 11)
Sleep(29)
MoveMouseRelative(0, 6)
Sleep(29)
MoveMouseRelative(0, 6)
Sleep(29)
MoveMouseRelative(0, 6)
Sleep(120)
Sleep(120)






                PressAndReleaseMouseButton(1)
                Sleep(25)

                
                



            until not IsMouseButtonPressed(1)
        end
    end
end